const LETTERS_ON_SCREEN = 8;
const X_MIN = 30;
const X_MAX = 630;
const Y_HEIGHT = 768;
const Y_STARTING_POINT = 40;
const MAX_STRIKES = 12;
const BOWL_WIDTH = X_MAX + X_MIN;
const BOWL_HEIGHT = 80;
const SPEED_UP_AFTER = 500;
const APP_ROOT_ELEMENT_ID = "game";
const GAME_SPEED = 1.005;
const GAME_SPEED_SMOOTHING = 10000;
const INITIAL_LETTERS_TIMEOUT = 2000;
const LETTERS_COLOR = "#000000";
const LETTERS_FONT = "Arial";
const BOWL_COLOR = "#1CA3EC";
const DEFAULT_CANVAS_WIDTH = 400;
const DEFAULT_CANVAS_HEIGHT = 300;

export default {
  LETTERS_ON_SCREEN,
  X_MAX,
  X_MIN,
  Y_HEIGHT,
  Y_STARTING_POINT,
  MAX_STRIKES,
  BOWL_WIDTH,
  BOWL_HEIGHT,
  SPEED_UP_AFTER,
  APP_ROOT_ELEMENT_ID,
  GAME_SPEED,
  GAME_SPEED_SMOOTHING,
  INITIAL_LETTERS_TIMEOUT,
  LETTERS_COLOR,
  LETTERS_FONT,
  BOWL_COLOR,
  DEFAULT_CANVAS_WIDTH,
  DEFAULT_CANVAS_HEIGHT,
};
